### ISSUE TITLE
Missing support for Apache 2.4

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [vkhatri/chef-pnp4nagios#5]
Included Apache templates doesn't work for Apache 2.4.

```
# apachectl -t
AH00526: Syntax error on line 11 of /etc/httpd/conf-enabled/pnp4nagios.conf:
Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration
```

**Comment by vkhatri** [comment]
@mateuszkwiatkowski will check it out, thanks for reporting!

**Comment by vkhatri** [comment]
@mateuszkwiatkowski added support for apache 2.4.

**Comment by mateuszkwiatkowski** [comment]
Many thanks!
17 maj 2015 9:22 AM Virender Khatri notifications@github.com napisał(a):@mateuszkwiatkowski added support for apache 2.4.
