### ISSUE TITLE
mod_python is not available in el7 (RHEL & CentOS)

### ISSUE THREAD

**Issue by spkane** [vkhatri/chef-pnp4nagios#7]
mod_python is not available in el7 and has been replaced by mod_wsgi.

If possible it would be ideal to alter this to work with mod_wsgi or to test for the platform and version and produce a useful error for users.

**Comment by vkhatri** [comment]
@spkane Thanks for reporting, will update cookbook.

**Comment by vkhatri** [comment]
@spkane Cookbook updated.

**Comment by spkane** [comment]
@vkhatri Thank you. That seemed to do the trick!
